apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Log output
  template:
    metadata:
      labels:
        app: Log output
    spec:
      containers:
        - name: Log output
          image: rashmika31601/logger:v1.0
